### ISSUE TITLE
[Add]: <ArtBlocks Multiple">

### ISSUE THREAD

**Issue by Dbochman** [DefiNavy/website-contributions#2]
### Section to add the link to

dApps - NFTs

### Link(s) to add

```shell
- [ArtBlocks](https://www.artblocks.io/){:target="_blank"}
- [ArtBlocksWiki](https://artblocks.wiki/){:target="_blank"}
```

### I know how to read

- [X] Yes, my submission is not duplicated

**Comment by dreth** [comment]
Thank you! I'll add it

**Comment by dreth** [comment]
Added: https://defi.navy/links/dapps_nfts/
